- name: Install docker packages
  #  remote_user: ubunt
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent
    - python3-pip
    - virtualenv
    - python3-setuptools
  tags:
    - docker

- name: Add Docker GPG apt Key
  become: yes
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  become_user: root
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt packages
  # remote_user: ubuntu
  apt:
  tags:
    - docker
- name: Install docker
  become: yes
  become_user: root
  # remote_user: ubuntu
  apt:
    name: docker-ce
    state: present
  #notify: Start docker on boot
  tags:
    - docker
- name: Add remote "ubuntu" user to "docker" group
  become: yes
  become_user: root
  # remote_user: ubuntu
  user:
    name: "ubuntu"
    group: "docker"
    append: yes
  tags:
    - docker
- name: Install docker-compose
  become: yes
  become_user: root
  # remote_user: ubuntu
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
