- name: "apt-get update"
  become: yes
  become_user: root
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "install nginx"
  become: yes
  become_user: root
  apt:
    name: ['nginx']
    state: latest

# - name: start nginx
#   # become: yes
#   service:
#       name: nginx
#       state: started

# - name: copy the nginx config file and restart nginx
#   copy:
#     src: ../{"role_name"}/files/{"Configuration_file_name"}
#     dest: /etc/nginx/sites-available/Configuration_file_name
#   # become: yes
# - name: create symlink
#   file:
#     src: /etc/nginx/sites-available/Configuration_file_name
#     dest: /etc/nginx/sites-enabled/default
#     state: link
#   # become: yes